title: evnL
description: >
  Irrationally rational. Meta-learning. Efficiency and creativity. Perception
  and curiosity. Welcome to the mind of evnL.
baseurl: "" 
url: "" 

author: &author "Evan Lee"
email: evnl.business@gmail.com
twitter_username: leaf2fire
github_username:  leaf2fire

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: *author