title: evnL
description: >
  A pragmatic philosopher and efficient ergonomist's irrationally rational
  ramblings on meta-learning, efficiency, creativity, perception, and curiosity.

baseurl: ""
url: "https://evnl.me"

author: &author "Evan Lee"
email: evnl.business@gmail.com
twitter_username: leaf2fire
github_username:  leaf2fire

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: *author